### ISSUE TITLE
BUG There is a second external highlight when the cursor hovers the icon.

### ISSUE THREAD

**Issue by MetotoSakamoto** [fthx/new-mail-indicator#10]
There is a second external highlight when the cursor hovers the icon.

![002](https://user-images.githubusercontent.com/16877755/115128785-881c9f80-9fe0-11eb-8018-2e0c2b20291d.png)

Gnome40

**Comment by fthx** [comment]
https://github.com/fthx/new-mail-indicator/commit/32e64c7e9ab7682b83058f8f733597babd462c7c

I did notice that on my Fedora 34 VM, but forgot to do something.
Will land in v. 31, uploaded to GS extensions website.
