### ISSUE TITLE
It's not working on Gnome 46

### ISSUE THREAD

**Issue by raulgrangeiro** [fthx/new-mail-indicator#16]
Friend, could you, please, make it compatible with Gnome 46? It's one of the best extensions we have.

**Comment by fthx** [comment]
Hi,

No sorry I won't update this one. There are changes in notification system in GS 46.

You can try to add "46" to metadata.json in ~/.local/share/gnome-shell/extensions/new-mail-indicator@fthx and restart session from gdm. It could work. If so, I'll update it.

**Comment by raulgrangeiro** [comment]
> Hi,
> 
> No sorry I won't update this one. There are changes in notification system in GS 46.
> 
> You can try to add "46" to metadata.json in ~/.local/share/gnome-shell/extensions/new-mail-indicator@fthx and restart session from gdm. It could work. If so, I'll update it.

I don't have the extension installed because I instaled Ubuntu 24.04 from scratch, and I can't install it anymore.

Why don't you want to update it anymore?

**Comment by fthx** [comment]
Ok it works with GS 46.
I upload it now, should be online very soon, once reviewed.

**Comment by raulgrangeiro** [comment]
> Ok it works with GS 46. I upload it now, should be online very soon, once reviewed.

Oh, man, thank you so much. Your extension really helps me. God bless you, friend!
