### ISSUE TITLE
Error: Invalid value 'undefined' for property body in object initializer.

### ISSUE THREAD

**Issue by St3v3-wq** [fthx/new-mail-indicator#17]
I just got this error in gnome-extensions and the extension would not start.

**Comment by fthx** [comment]
You run Arch?
I got another similar bug in Proton VPN button extension.

The bug is due to the new notification syntax (needs two args in GS 46) that I did forget to change.
BUT that's not the root cause.
The cause is the app is not found.

Do you know how to use looking glass in gnome shell?

**Comment by fthx** [comment]
btw I don't get any error using Ubuntu 24.04.

**Comment by St3v3-wq** [comment]
No, Fedora 40.

**Comment by fthx** [comment]
What's your email client?
Is it set as default email client in GS prefs?

**Comment by St3v3-wq** [comment]
What's your email client? Evolution (RPM)
Is it set as default email client in GS prefs? Yes

This is strange: I installed claws-mail, then the extension is working. But only with claws, even when evolution is set in GS. When I remove claws, the error is something like "failed to open claws-mail, failure in PATH".

**Comment by fthx** [comment]
Ok. Maybe a session restart is needed for email client switch.

Please in GNOME Shell:
- alt+F2 (execute)
- lg (looking glass inspector)
- enter this: GLib.spawn_command_line_sync("xdg-mime query default x-scheme-handler/mailto")
- copy here the result

**Comment by St3v3-wq** [comment]
![Screenshot from 2024-07-15 12-21-25](https://github.com/user-attachments/assets/5f033c6e-e841-4212-8e4b-f4cf4383a708)
I'm sorry, lg is unsupported. Is there a new version somewhere? Also when I install it anyway..

**Comment by fthx** [comment]
LG is not an extension, it's built-in 
I've installed a F40 vm and the result is a void name, so the error.

**Comment by fthx** [comment]
![image](https://github.com/user-attachments/assets/3d2da5bc-c4c2-4933-9daa-2822e794696c)

**Comment by fthx** [comment]
Damn Software app, soooo slow. I'm back soon ;-)

**Comment by fthx** [comment]
Ok I installed Evolution, will be better now ;-)

**Comment by fthx** [comment]
Mmmh I get all attended prompts?
![image](https://github.com/user-attachments/assets/78a9df01-e7bc-49fe-ad4d-cd13bc7a289c)

**Comment by St3v3-wq** [comment]
Ok, here the output from lg: ...true,org.Evolution.desktop...

**Comment by fthx** [comment]
It works in my VM:

![image](https://github.com/user-attachments/assets/175aa642-5810-4915-a7fb-f0b11665f727)

**Comment by fthx** [comment]
The button click works too.

**Comment by St3v3-wq** [comment]
hmm?

**Comment by fthx** [comment]
Did you set this (again)?

![image](https://github.com/user-attachments/assets/6cd7d64c-9873-45bf-9b8b-473c9d97d960)

**Comment by St3v3-wq** [comment]
![Screenshot from 2024-07-15 12-42-05](https://github.com/user-attachments/assets/6fd8680c-a230-448a-ac1d-6331a9e00603)
![Screenshot from 2024-07-15 12-41-23](https://github.com/user-attachments/assets/85610dae-f6a5-4973-8868-1d76b8954f03)
![Screenshot from 2024-07-15 12-40-46](https://github.com/user-attachments/assets/f0da5f92-1e27-47d9-b1d5-17b943f0f76b)

**Comment by St3v3-wq** [comment]
It does not even start without claws-mail??

**Comment by fthx** [comment]
Did you try without any other extension disabled?

**Comment by fthx** [comment]
What's the command in terminal to update rpm packages, please?

**Comment by St3v3-wq** [comment]
sudo dnf update

**Comment by St3v3-wq** [comment]
Maybe this is a "only my computer" problem. Sorry. Should I delete some Gnome Settings?

**Comment by fthx** [comment]
I cannot install Claws, it's failing...

**Comment by fthx** [comment]
Do you have the black square in LG at the end of org.Ev... ?
(That's attended.)

**Comment by fthx** [comment]
Could you change this line in:
~/.local/share/gnome-shell/extensions/new-mail-indicator/extensions.js
?

48          Main.notify("New Mail Indicator: error, no email client found");

to:

Main.notify("New Mail Indicator: error, no email client found", "");

**Comment by fthx** [comment]
Then restart your session.

**Comment by St3v3-wq** [comment]
> Do you have the black square in LG at the end of org.Ev... ? (That's attended.)

Yes, it's white here.

**Comment by St3v3-wq** [comment]
Yep, it's running now (error, no email client found).

**Comment by fthx** [comment]
Well that's annoying I cannot reproduce the root cause in VM.
Maybe an update since F40 iso has changed something?

**Comment by St3v3-wq** [comment]
It was running with Evolution from Flatpak, but not anymore. That is strange.

**Comment by fthx** [comment]
As a workaround you can change this:

    _find_default_client() {
        this._decoder = new TextDecoder();
        this._app_query = GLib.spawn_command_line_sync("xdg-mime query default x-scheme-handler/mailto");
        this._app_filename = this._decoder.decode(this._app_query[1].slice(0,-1));
        this._app = Shell.AppSystem.get_default().lookup_app(this._app_filename);
        if (this._app) {
            this._app_name = this._app.get_name();
        } else {
            Main.notify("New Mail Indicator: error, no email client found");
        }
    }

to this:

    _find_default_client() {
        this._app_name = "Evolution";
    }

**Comment by fthx** [comment]
but you won't have the click feature since I catch the app object's windows.

**Comment by fthx** [comment]
in LG did you try:

Shell.AppSystem.get_default().lookup_app("org.gnome.Evolution.desktop")

?

**Comment by St3v3-wq** [comment]
Ok, thank You for this.

> in LG did you try:
> 
> Shell.AppSystem.get_default().lookup_app("org.gnome.Evolution.desktop")
> 
> ?

r(0) = null

**Comment by St3v3-wq** [comment]
Oh sorry, I forgot to say: There is a bug in the current Evolution installation and there ist no org.gnome.Evolution.desktop. Is this maybe the problem? I mean, there is no Icon to start Evolution.

**Comment by St3v3-wq** [comment]
> As a workaround you can change this:
> 
> ```
> _find_default_client() {
>     this._decoder = new TextDecoder();
>     this._app_query = GLib.spawn_command_line_sync("xdg-mime query default x-scheme-handler/mailto");
>     this._app_filename = this._decoder.decode(this._app_query[1].slice(0,-1));
>     this._app = Shell.AppSystem.get_default().lookup_app(this._app_filename);
>     if (this._app) {
>         this._app_name = this._app.get_name();
>     } else {
>         Main.notify("New Mail Indicator: error, no email client found");
>     }
> }
> ```
> 
> to this:
> 
> ```
> _find_default_client() {
>     this._app_name = "Evolution";
> }
> ```

Thank You for that. It's running now, with the error: Error: Invalid value 'undefined' for property body in object initializer.

**Comment by fthx** [comment]
For Ev install, you have to check in /usr/share/applications

**Comment by St3v3-wq** [comment]
> For Ev install, you have to check in /usr/share/applications

Ah, tere is it...

**Comment by St3v3-wq** [comment]
> As a workaround you can change this:
> 
> ```
> _find_default_client() {
>     this._decoder = new TextDecoder();
>     this._app_query = GLib.spawn_command_line_sync("xdg-mime query default x-scheme-handler/mailto");
>     this._app_filename = this._decoder.decode(this._app_query[1].slice(0,-1));
>     this._app = Shell.AppSystem.get_default().lookup_app(this._app_filename);
>     if (this._app) {
>         this._app_name = this._app.get_name();
>     } else {
>         Main.notify("New Mail Indicator: error, no email client found");
>     }
> }
> ```
> 
> to this:
> 
> ```
> _find_default_client() {
>     this._app_name = "Evolution";
> }
> ```

But this way does not  display new Mails (red icon).

However, thank You for Your time!

**Comment by St3v3-wq** [comment]
Ok, fixed.

I fixed it by fixing Evolution. There is no problem with Your extension. The way was (at the end very easy):

$ cp /usr/share/applications/org.gnome.Evolution.desktop ~/.local/share/applications/
$ update-desktop-database -v ~/.local/share/applications

Thanks for Your time!
