### ISSUE TITLE
Nice extension, but since v14 it keeps crashing.

### ISSUE THREAD

**Issue by llcool** [fthx/new-mail-indicator#2]
Nice extension, but since v14 it keeps crashing.

Ubuntu 19.10
GNOME Shell 3.34.3

This error is from new-mail-indicator version 18
I am now running v14 without any crashes

gnome-shell[3032]: JS ERROR: Extension new-mail-indicator@fthx: Error: No signal connection function wrapper(...args) {#012 let prevCaller = this.__caller__;#012 this.__caller__ = wrapper;#012 let result = meth.apply(this, args);#012 this.__caller__ = prevCaller;#012 return result;#012 } found#012_disconnect@resource:///org/gnome/gjs/modules/signals.js:79:11#012_destroy@/home/lloyd/.local/share/gnome-shell/extensions/new-mail-indicator@fthx/extension.js:100:6#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012disable@/home/lloyd/.local/share/gnome-shell/extensions/new-mail-indicator@fthx/extension.js:119:2#012_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:96:13#012_disableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:524:17#012_disableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:523:13#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:541:13#012_emit@resource:///org/gnome/gjs/modules/signals.js:135:27#012_sync@resource:///org/gnome/shell/ui/sessionMode.js:207:9#012pushMode@resource:///org/gnome/shell/ui/sessionMode.js:169:9#012activate@resource:///org/gnome/shell/ui/screenShield.js:1275:17#012lock@resource:///org/gnome/shell/ui/screenShield.js:1324:9#012_onStatusChanged/this._lockTimeoutId<@resource:///org/gnome/shell/ui/screenShield.js:853:21
Apr 20 09:56:06 lloyd-ThinkCentre-E73 gnome-software[4347]: new-mail-indicator_fthx has error: Error: No signal connection function wrapper(...args) {#012 let prevCaller = this.__caller__;#012 this.__caller__ = wrapper;#012 let result = meth.apply(this, args);#012 this.__caller__ = prevCaller;#012 return result;#012 } found

**Comment by fthx** [comment]
Thanks for reporting. I've got a lot of BR for older GS 3.28 too.

Please update your extension with version 20 (to be reviewed) https://extensions.gnome.org/review/download/16054.shell-extension.zip or this github's files. Tell me if it's ok for you (I don't have a 19.10 VM, just a 18.04 one, and it does work well on it).

**Comment by llcool** [comment]
Had some initial errors when I update to v20 But after rebooting my PC and sending a email no more errors. Thanks great work. :+1: 

My initial errors before rebooting:-
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: == Stack trace for context 0x5636aedc1570 ==
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: Object St.Bin (0x5636b713a0c0), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destro
yed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #0   5636c9a648a8 i   /home/lloyd/.local/share/gnome-shell/extensions/new-mail-indicator@fthx/extension.js:80 (7fe3f55289d0 @ 68)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #1   5636c9a64808 i   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fe3f5bb20d0 @ 69)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #2   7ffd659e2850 b   self-hosted:979 (7fe3f5235670 @ 440)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #3   7ffd659e2940 b   resource:///org/gnome/gjs/modules/signals.js:135 (7fe3f5bc7280 @ 376)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #4   5636c9a64688 i   resource:///org/gnome/shell/ui/messageTray.js:1018 (7fe3f55b0160 @ 182)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #5   5636c9a645f0 i   resource:///org/gnome/shell/ui/messageTray.js:1041 (7fe3f55b0310 @ 90)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #6   5636c9a64558 i   resource:///org/gnome/shell/ui/messageTray.js:1004 (7fe3f55b0040 @ 198)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #7   5636c9a644b0 i   resource:///org/gnome/shell/ui/notificationDaemon.js:149 (7fe3f53ca0d0 @ 320)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #8   5636c9a64408 i   resource:///org/gnome/shell/ui/notificationDaemon.js:249 (7fe3f53ca310 @ 265)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #9   5636c9a64360 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:132 (7fe3f5bd4ee0 @ 248)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: == Stack trace for context 0x5636aedc1570 ==
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #0   5636c9a648a8 i   /home/lloyd/.local/share/gnome-shell/extensions/new-mail-indicator@fthx/extension.js:81 (7fe3f55289d0 @ 100)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #1   5636c9a64808 i   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fe3f5bb20d0 @ 69)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #2   7ffd659e2850 b   self-hosted:979 (7fe3f5235670 @ 440)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #3   7ffd659e2940 b   resource:///org/gnome/gjs/modules/signals.js:135 (7fe3f5bc7280 @ 376)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #4   5636c9a64688 i   resource:///org/gnome/shell/ui/messageTray.js:1018 (7fe3f55b0160 @ 182)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #5   5636c9a645f0 i   resource:///org/gnome/shell/ui/messageTray.js:1041 (7fe3f55b0310 @ 90)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #6   5636c9a64558 i   resource:///org/gnome/shell/ui/messageTray.js:1004 (7fe3f55b0040 @ 198)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #7   5636c9a644b0 i   resource:///org/gnome/shell/ui/notificationDaemon.js:149 (7fe3f53ca0d0 @ 320)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #8   5636c9a64408 i   resource:///org/gnome/shell/ui/notificationDaemon.js:249 (7fe3f53ca310 @ 265)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: #9   5636c9a64360 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:132 (7fe3f5bd4ee0 @ 248)
Apr 22 14:20:46 lloyd-ThinkCentre-E73 gnome-shell[3032]: == Stack trace for context 0x5636aedc1570 ==
