### ISSUE TITLE
Separate new mail indicator extension for Thunderbird (maybe Evolution)

### ISSUE THREAD

**Issue by Filbuntu** [fthx/new-mail-indicator#3]
Hi François
Thanks for [offering to look into making two separate extensions](https://discourse.ubuntu.com/t/evolution-again-as-default-email-app-client/15457/46?u=tellapu), one for TB, one for Evo, with optional text labels to make the indicators distinguishable. 
I would be interested to get one for Thunderbird, at the moment I would not need a label as Evolution shows a counter badge in the dock and I would only install the TB mail indicator and space in the panel is usually scarce on my screen.
Depending how much work it is, I wonder whether to keep the original new-mail-indicator for the ones who don't use several email clients or Geary, Mailspring.
Thanks again for your offer but don't feel pressurised if you don't have time at hand.

**Comment by fthx** [comment]
Well, I'll wait for other users asking the same feature.
Waiting for that, you can check the extension.js code and just delete the default email app detection.

Delete : 
```
let defaultMailAppFilename = ByteArray.toString(GLib.spawn_command_line_sync("xdg-mime query default x-scheme-handler/mailto")[1]).slice(0,-1);

// get the default mail client's executable command
let defaultMailAppExe;
let defaultMailAppName;
let defaultMailAppExeAlt;
switch (defaultMailAppFilename) {
  case "thunderbird.desktop":
  case "mozilla-thunderbird.desktop":
    defaultMailAppExe = "thunderbird";
    defaultMailAppName = "Thunderbird";
    break;
  case "org.gnome.Evolution.desktop":
    defaultMailAppExe = "evolution -c mail";
    defaultMailAppName = "Evolution";
    break;
  case "org.gnome.Geary.desktop":
    defaultMailAppExe = "geary";
    defaultMailAppExeAlt = "flatpak run org.gnome.Geary";
    defaultMailAppName = "Geary";
    break;
  case "mailspring_mailspring.desktop":
  	defaultMailAppExe = "mailspring";
  	defaultMailAppName = "Mailspring";
  	break;
  default:
    Main.notify("New Mail Indicator: error, no known email client found.");
};
```
Replace by: 
```
let defaultMailAppExe = "thunderbird";
let defaultMailAppName = "Thunderbird";
```

**Comment by Filbuntu** [comment]
Thanks a lot! It works!  
Although I still prefer a new email counter/badge on the Thunderbird icon on the Dock ([or similar: Thunderbird needs a persistent "new mail" indicator on Linux](https://bugzilla.mozilla.org/show_bug.cgi?id=1482674)), this is a nice workaround!

**Comment by fthx** [comment]
I do use a GNOME session, not Dash to Dock. So a badge is useless here.
Of course in your case it would be much better integrated.

Note that legacy TB notifications (with correct timeout set) are persistent.

**Comment by Filbuntu** [comment]
> I do use a GNOME session, not Dash to Dock. So a badge is useless here.
> Of course in your case it would be much better integrated.

I understand that when you have no Dash to Dock, a badge is of no use. And your extension is nice and nifty support! Thanks again!

> Note that legacy TB notifications (with correct timeout set) are persistent.

This is a good to know! I wanted to refer to the need for a counter/badge for the Dash to Dock. Sorry for the mix-up.

Thanks again!

**Comment by fthx** [comment]
I close this as there's no additional request.
Every other user can feel free to reopen it.

**Comment by Filbuntu** [comment]
Thanks for help again!
That is fine although I hoped somebody else would like this 😀, too.  It works with your [tipp](https://github.com/fthx/new-mail-indicator/issues/3#issuecomment-653425994) but I had to re-do recently, maybe after an update.

**Comment by fthx** [comment]
Yes I committed an update to manage Thunderbird snap version. It should be quiet now. :-)

**Comment by Filbuntu** [comment]
No problem, I like updates :).

**Comment by Filbuntu** [comment]
Bonsoir François
Thank you for updating the mail indicator app! 
Probably you had to change quite a lot and the work around mentioned above does not work anymore.

I tried to edit this section like below:
 `   // get the default email client filename, name, executable and app
	this.default_mail_app_exe = "thunderbird";
	this.default_mail_app_name = "Thunderbird";`

After Alt+F2 and r, it still does not work. At least the new emails in Evolution don't trigger the indicator sign anymore. Any other tip to make the mail indicator appear only with a new email in Thunderbird?

**Comment by fthx** [comment]
Hi,

Change:

```
// get the default email client filename, name, executable and app
    _find_default_client() {
   <.................>
    }
```

to:

```
// get the default email client filename, name, executable and app
    _find_default_client() {
	this.default_mail_app_exe = "thunderbird";
	this.default_mail_app_name = "Thunderbird";
	this.app = Shell.AppSystem.get_default().lookup_app("mozilla-thunderbird.desktop");
  }
```

**Comment by fthx** [comment]
It will run with Ubuntu/Debian.
If you do use Fedora, change "mozilla-thunderbird.desktop" to "thunderbird .desktop".
If you do use Snap (like me), to "thunderbird_thunderbird.desktop".

I need app object to track the email client window for the new click-icon-to-toggle feature. So this.app = ... is needed now.

**Comment by Filbuntu** [comment]
Wow, that was lightening fast! 
I did as recommended by somehow it did not work (also after Alt+F2 and r). I will try again after a restart tomorrow or so.
Thanks again!

**Comment by fthx** [comment]
Uh, that's probably my fault.
Use "thunderbird.desktop". I cannot check that again because I run snap TB version.
In a terminal you can go to /usr/share/applications and list file with ls command. You'll find your TB desktop filename!

**Comment by Filbuntu** [comment]
Well guessed! Yes, it is it! Thanks a lot!

**Comment by fthx** [comment]
You could be interested in:
https://extensions.gnome.org/extension/3951/persistent-email-notifications
It's another way to achieve the same goal: not missing an email notification. I've just finished it last night and Andy Holmes reviewed it very very quickly. This new extension is much less hacky than already published ones.
Why did I wrote this? Because of another one from last night:
https://extensions.gnome.org/extension/3948/hide-panel
With no panel except in overview, an indicator is much less useful...

Both extensions are very light, laptop-minded. If you're interested in the first one, you'll find in its extension.js headers a list of email clients to handle for persistent notifications.

**Comment by Filbuntu** [comment]
You are really productive, thanks a lot! I will test the persistent email notification extension.
