### ISSUE TITLE
Execution of “undefined” failed

### ISSUE THREAD

**Issue by Spurlos** [fthx/new-mail-indicator#4]
All of a sudden this error appears when clicking the mail icon. Full restart didn't help
```
Oct  6 13:53:19 spurlos-ThinkPad-E580 gnome-shell[3877]: error: Execution of “undefined” failed:: Expected type filename for Argument 'command_line' but got type 'undefined'
```

**Comment by fthx** [comment]
There was no recent update. So it must be another software change.

What Gnome Shell version?
What distribution?
What extension version?
What is your default email client? Snap, Flatpak?

Did you uncomment the lines
```
// for debug purposes you can uncomment the next line: it will pop-up the default mail client above names
//Main.notify(defaultMailAppFilename+"  "+defaultMailAppExe+"  "+defaultMailAppName);
```
in extension.js?

**Comment by Spurlos** [comment]
**Versions**
Gnome: 3.36.3
Distro: Ubuntu 20.04
Extension: 22

Default email client: Thunderbird (deb)

I haven't uncommented those lines.

While I was double checking the default mail client I have noticed multiple Thunderbird records in the dropdown. Strangely enough I haven't installed any additional Thunderbird clients. Setting the one with icon and restarting Gnome helped to solve this issue.
![Peek 2020-10-06 17-38](https://user-images.githubusercontent.com/667533/95217428-d7953e00-07fb-11eb-9db6-e77971d8d63d.gif)

**Comment by fthx** [comment]
There's something odd in your config. I do use the same Ubuntu and:

![image](https://user-images.githubusercontent.com/23138504/95223584-0e6a5480-07fa-11eb-968b-17c59b2873d8.png)

I do use TB snap but I very recently was using TB deb with the same extension version.
