### ISSUE TITLE
Problem with Evolution

### ISSUE THREAD

**Issue by davidbenucci** [fthx/new-mail-indicator#6]
When i click on the icon I see "thunderbird : command not found". But my default email client is Evolution. How can I solve?
I'm on ubuntu 20.04

**Comment by fthx** [comment]
I recently used Evolution without any issue?
I do use Ub 20.04 too.

Could you check and screenshot the Default Apps settings in Gnome control center ?

**Comment by davidbenucci** [comment]
Here you are. Thanks.
![Evolution](https://user-images.githubusercontent.com/25527097/95551122-6e374a00-0a0a-11eb-835b-eab019072c53.png)

**Comment by fthx** [comment]
Do you have any Thunderbird in Email menu, beside Evolution ?
Did you install any Thunderbird in the past, including from tarball ?
Could you give me the result of : 
`xdg-mime query default x-scheme-handler/mailto`
in a terminal ?

**Comment by davidbenucci** [comment]
It's thunderbird.desktop. How can I change it and set to evolution? thanks

**Comment by fthx** [comment]
If you have TB installed, just switch it two times in gnome control center.

**Comment by davidbenucci** [comment]
Ok, thanks.
